# Muj pierwszy workflow
# Od .NETa więcej info tutaj: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true # bo przecież korzystamy z klasy
    - name: Ustaw .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
      run: dotnet tool install --global Microsoft.Sbom.DotNetTool
    - name: Przywróć wymagane pakiety
      run: dotnet workload restore
    - name: I jeszcze coś
      run: dotnet restore --verbosity diagnostic
    - name: Zbuduj
      run: dotnet build --no-restore --configuration Debug --verbosity diagnostic --runtime win-x64
    #- name: SBOM
     # run: sbom-tool generate
    - name: Testuj
      run: dotnet test --no-build --verbosity normal
  praca:
    runs-on: ubuntu-latest
    steps:
    - name: na wszelki wypadek ściągnijmy repo z klasą
      uses: actions/checkout@v4
      with:
        repository: ebrulf/SGGW-Thesis-LaTeX
        path: latex/cls
    - name: Skompiluj LaTeX-a
      uses: xu-cheng/latex-action@v3
      with:
        #working_directory: praca #może teraz znajdzie
        root_file: praca/praca.tex
        texlive_version: 2024 #doprecyzujmy
        re_compile: "tlmgr update --self && tlmgr update --all"
        latexmk_use_xelatex: false #pdfTeX albo przewóz
        #env:
        #  TEXINPUTS: "./latex/cls//:"
        args: -pdf -bibtex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    - name: Wrzuć PDF-a
      uses: actions/upload-artifact@v4
      with:
        name: praca
        path: praca/praca.pdf
