# Muj pierwszy workflow
# Od .NETa więcej info tutaj: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true # bo przecież korzystamy z klasy
    - name: Ustaw .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Przywróć wymagane pakiety
      run: dotnet workload restore
    - name: I jeszcze coś
      run: dotnet restore
    - name: Zbuduj
      run: dotnet build --no-restore
    - name: Testuj
      run: dotnet test --no-build --verbosity normal
  praca:
    runs-on: ubuntu-latest
    steps:
    - name: na wszelki wypadek ściągnijmy repo z klasą
      uses: actions/checkout@v4
      with:
        repository: ebrulf/SGGW-Thesis-LaTeX
        path: latex/cls
    - name: Skompiluj LaTeX-a
      uses: xu-cheng/latex-action@v3
      with:
        working_directory: praca
        root_file: praca.tex
        latexmk_use_xelatex: true
        env:
          TEXINPUTS: ".:./latex/cls//:"
        #args: -pdf -bibtex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode
    - name: Wrzuć PDF-a
      uses: actions/upload-artifact@v4
      with:
        name: praca
        path: praca/praca.pdf
